// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGy-wAPq027d4KeFSH9T5b3SCZZ3S3jb8',
    appId: '1:335555253662:web:d17de48b0a92e729ddf28f',
    messagingSenderId: '335555253662',
    projectId: 'ecommerceapp-968fe',
    authDomain: 'ecommerceapp-968fe.firebaseapp.com',
    storageBucket: 'ecommerceapp-968fe.appspot.com',
    measurementId: 'G-SLKPSM347Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNfEP0ExkGX_1D5HVoEOTnLxAEqkCDP8',
    appId: '1:335555253662:android:eb0f27fc8e3cdaa2ddf28f',
    messagingSenderId: '335555253662',
    projectId: 'ecommerceapp-968fe',
    storageBucket: 'ecommerceapp-968fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRVQazj449j_4tsZq4XPjWDxVHDklJgXQ',
    appId: '1:335555253662:ios:8669a7b9c2c186bcddf28f',
    messagingSenderId: '335555253662',
    projectId: 'ecommerceapp-968fe',
    storageBucket: 'ecommerceapp-968fe.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRVQazj449j_4tsZq4XPjWDxVHDklJgXQ',
    appId: '1:335555253662:ios:8669a7b9c2c186bcddf28f',
    messagingSenderId: '335555253662',
    projectId: 'ecommerceapp-968fe',
    storageBucket: 'ecommerceapp-968fe.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGy-wAPq027d4KeFSH9T5b3SCZZ3S3jb8',
    appId: '1:335555253662:web:2e28ed82a6fe6c5addf28f',
    messagingSenderId: '335555253662',
    projectId: 'ecommerceapp-968fe',
    authDomain: 'ecommerceapp-968fe.firebaseapp.com',
    storageBucket: 'ecommerceapp-968fe.appspot.com',
    measurementId: 'G-CGNQD1VQVE',
  );
}
